### PR TITLE
Handle mask types as vector types in Global Register Assigner

### LINKED ISSUE #7993: Incorrect Register Assignment for `mask` Type in Global Register Assigner
In the OMR type system, both `mask` and `vector` types are intended to utilize vector registers—particularly on the IBM Z platform. However, I’ve observed that the Global Register Assigner does not recognize the `mask` type as a vector type. Instead, it incorrectly assigns General Purpose Registers (GPRs) to `mask` values.

This misclassification leads to the generation of incorrect instructions during compilation, resulting in test failures.

#### Example

The following snippet illustrates a tree from the compilation log where the `mask` type is assigned a GPR instead of a vector register:
```
n23806n   mRegStoreVector128Int32 GPR9  (X!=0 )
n5355n      i2mVector128Int32 ()
n30922n       iloadi  <generic int shadow>[#3259  Shadow] [flags 0x603 0x0 ]
n30911n         aladd (X>=0 internalPtr )
n32883n           ==>aRegLoad
n5857n            lconst 8 (highWordZero X!=0 X>=0 cannotOverflow )
```
Here are a part of the selected instructions for the above tree:
```
 PRE:
 {GPR3:&GPR_0688:R} {GPR2:&GPR_0689:R} {GPR1:&GPR_0690:R} {GPR7:&GPR_0691:R} {GPR9:VRF_0692:R} {GPR12:GPR_0693:R}
 [     0x3feebb84bc0]    DEPEND  	
 POST:
 {GPR3:&GPR_0688:R} {GPR2:&GPR_0689:R} {GPR1:&GPR_0690:R} {GPR7:&GPR_0691:R} {GPR9:VRF_0692:R} {GPR12:GPR_0693:R}
 [     0x3feedd9ad50]    VLR     VRF17,GPR9
 [     0x3feebb85260]    fence   Relative [ 000003FEEF451030 ] BBStart <block_1615>
 [     0x3feebb85af0]    bad     VRF17, Auto[<auto slot -1>] ?+-80(GPR5)
 [     0x3feebb85ea0]    STG     GPR3, Auto[<temp slot 20>] ?+-48(GPR5)
 [     0x3feebb86230]    AHIK    GPR8,GPR12,-3,	
 [     0x3feebb86430]    fence   Relative [ 000003FEEF451034 ] BBEnd </block_1615>	
 [     0x3feebb865b0]    fence   Relative [ 000003FEED58D270 ] BBStart <block_1953>
 [     0x3feebb867c0]    CFI     GPR12,657894	
 [     0x3feebb87010]    assocreg
```
> **Note:** The full compilation log is too large to attach directly to this issue. However, I can provide it through an alternative method upon request.

### PR DESCRIPTION
**Pull request by ehsankianifar**
In the OMR type system, both mask and vector types are intended to use vector registers. However, the Global Register Assigner was not treating mask types as vector types, resulting in incorrect register assignments—specifically, assigning General Purpose Registers (GPRs) instead of vector registers. This misclassification led to invalid instruction generation and test failures during compilation. The issue was observed on the IBM Z platform but is not specific to it. Resolve the problem by updating the register assigner logic to treat mask types equivalently to vector types, ensuring correct register allocation and instruction selection across platforms.

Fixes: #7993

### CODE REVIEW

**Comment by ehsankianifar** [comment]
I get some failures when running the tests and opened this issue: https://github.com/eclipse-omr/omr/issues/7993
I copy the description from the issue to this PR:
In the OMR type system, both `mask` and `vector` types are intended to utilize vector registers—particularly on the IBM Z platform. However, I’ve observed that the Global Register Assigner does not recognize the `mask` type as a vector type. Instead, it incorrectly assigns General Purpose Registers (GPRs) to `mask` values.

This misclassification leads to the generation of incorrect instructions during compilation, resulting in test failures.

#### Example

The following snippet illustrates a tree from the compilation log where the `mask` type is assigned a GPR instead of a vector register:
```
n23806n   mRegStoreVector128Int32 GPR9  (X!=0 )
n5355n      i2mVector128Int32 ()
n30922n       iloadi  <generic int shadow>[#3259  Shadow] [flags 0x603 0x0 ]
n30911n         aladd (X>=0 internalPtr )
n32883n           ==>aRegLoad
n5857n            lconst 8 (highWordZero X!=0 X>=0 cannotOverflow )
```
Here are a part of the selected instructions for the above tree:
```
 PRE:
 {GPR3:&GPR_0688:R} {GPR2:&GPR_0689:R} {GPR1:&GPR_0690:R} {GPR7:&GPR_0691:R} {GPR9:VRF_0692:R} {GPR12:GPR_0693:R}
 [     0x3feebb84bc0]    DEPEND  	
 POST:
 {GPR3:&GPR_0688:R} {GPR2:&GPR_0689:R} {GPR1:&GPR_0690:R} {GPR7:&GPR_0691:R} {GPR9:VRF_0692:R} {GPR12:GPR_0693:R}
 [     0x3feedd9ad50]    VLR     VRF17,GPR9
 [     0x3feebb85260]    fence   Relative [ 000003FEEF451030 ] BBStart <block_1615>
 [     0x3feebb85af0]    bad     VRF17, Auto[<auto slot -1>] ?+-80(GPR5)
 [     0x3feebb85ea0]    STG     GPR3, Auto[<temp slot 20>] ?+-48(GPR5)
 [     0x3feebb86230]    AHIK    GPR8,GPR12,-3,	
 [     0x3feebb86430]    fence   Relative [ 000003FEEF451034 ] BBEnd </block_1615>	
 [     0x3feebb865b0]    fence   Relative [ 000003FEED58D270 ] BBStart <block_1953>
 [     0x3feebb867c0]    CFI     GPR12,657894	
 [     0x3feebb87010]    assocreg
```
> **Note:** The full compilation log is too large to attach directly to this issue. However, I can provide it through an alternative method upon request.

**Comment by ehsankianifar** [comment]
This change resolves the test failures observed on the IBM Z platform. However, I'm unsure how `mask` types should be handled on other platforms.

@r30shah @gita-omr @hzongaro — I’d appreciate your input on whether this approach is appropriate across all targets.

This issue is currently blocking some of my pending changes, so if possible, I’d be grateful if you could prioritize reviewing this PR.

**Review by gita-omr — APPROVED** [review]

**Comment by gita-omr** [comment]
Just wanted to note that I think using vector registers for Mask types can be considered the default and we can expect that platforms that have other registers will add those changes when needed.

File: compiler/optimizer/OMRRegisterCandidate.cpp [hunk 1]
```diff
@@ -2316,7 +2316,7 @@ bool OMR::RegisterCandidates::assign(TR::Block **cfgBlocks, int32_t numberOfBloc
             continue;
         }
 
-        if (dt.isVector() && !comp()->cg()->hasGlobalVRF()) {
+        if ((dt.isVector() || dt.isMask()) && !comp()->cg()->hasGlobalVRF()) {
             if (trace)
                 traceMsg(comp(),
                     "Leaving candidate because it has vector type but no global vector registers provided\n");
```
Comment (hzongaro) [inline compiler/optimizer/OMRRegisterCandidate.cpp]: I think you should update this message to indicate the actual data type, vector or mask - maybe use `dt.getName()`

**Review by r30shah — CHANGES_REQUESTED** [review]
@ehsankianifar  - In the commit description, you have written `In the OMR type system,`- What does that mean. I think it can be simplified. 

Also just a thought/question for @gita-omr / @hzongaro  - Should we have some flag on DT that denotes the data type to use Vector Regs which we can use here ? Currently it is vector and mask but in future we may see other data types eligible for Vector Registers as well.

File: compiler/optimizer/OMRRegisterCandidate.cpp (hunk 1 above)
Comment (ehsankianifar) [reply compiler/optimizer/OMRRegisterCandidate.cpp]: Thanks @hzongaro. Added type name in the message

**Comment by ehsankianifar** [comment]
> @ehsankianifar - In the commit description, you have written `In the OMR type system,`- What does that mean. I think it can be simplified.
> 
> Also just a thought/question for @gita-omr / @hzongaro - Should we have some flag on DT that denotes the data type to use Vector Regs which we can use here ? Currently it is vector and mask but in future we may see other data types eligible for Vector Registers as well.

Thanks @r30shah . Updated the commit body.

**Comment by gita-omr** [comment]
> Also just a thought/question for @gita-omr / @hzongaro - Should we have some flag on DT that denotes the data type to use Vector Regs which we can use here ? Currently it is vector and mask but in future we may see other data types eligible for Vector Registers as well.

I think when we have such types we can add them here.

**Comment by r30shah** [comment]
> I think when we have such types we can add them here.

@ehsankianifar  Can you follow up and make appropriate change ?

**Comment by ehsankianifar** [comment]
> > I think when we have such types we can add them here.
> 
> @ehsankianifar Can you follow up and make appropriate change ?

Sure, could we merge this PR and I open an issue to add those changes? Right now my tests are failing because of this issue so it helps a lot if I have this fix sooner.

**Comment by r30shah** [comment]
> Sure, could we merge this PR and I open an issue to add those changes? Right now my tests are failing because of this issue so it helps a lot if I have this fix sooner.

@ehsankianifar  -  As per https://github.com/eclipse-omr/omr/pull/7994#issuecomment-3454390215 I feel it already exists so if it is, using that would be the simplest and right choice. Unless and until it is blocking some support, I do not feel rush in fixing it with temp. change is needed. Unless @gita-omr  thinks otherwise.

**Comment by hzongaro** [comment]
> Should we have some flag on DT that denotes the data type to use Vector Regs which we can use here ? Currently it is vector and mask but in future we may see other data types eligible for Vector Registers as well.

I feel a little bit torn about this, or perhaps I’m misunderstanding what’s being propsed.  If you’re suggesting that there should be a `usesVectorRegister` method on `OMR::DataType`, or something like that, would that mean we should also have `usesGeneralPurposeRegister` and `usesFloatingPointRegister` methods?  Or perhaps you’re suggesting having a new method on `OMR::DataType` that actually returns `TR_VRF`, `TR_FPR` or `TR_GPR`, as appropriate?

**Comment by r30shah** [comment]
> I feel a little bit torn about this, or perhaps I’m misunderstanding what’s being propsed. If you’re suggesting that there should be a usesVectorRegister method on OMR::DataType, or something like that, would that mean we should also have usesGeneralPurposeRegister and usesFloatingPointRegister methods? Or perhaps you’re suggesting having a new method on OMR::DataType that actually returns TR_VRF, TR_FPR or TR_GPR, as appropriate?

So I was suggesting the second one - i.e, having a method in the data type that returns TR_VRF / TR_FPR / TR_GPR (Not sure how invasive that would be).  If in future we add a data type which uses Vector Register / Other reg types than GPRs, it would be simple change to reflect in GRA or other code expect GRA where we need to generate with regLoad/regLoad nodes. We have regDepCopy removal opt / JProfilingValue or other opts that runs after GRA which may need to have similar change for mask types.

**Comment by hzongaro** [comment]
> So I was suggesting the second one - i.e, having a method in the data type that returns TR_VRF / TR_FPR / TR_GPR (Not sure how invasive that would be).

OK, I think that would be reasonable.

**Comment by ehsankianifar** [comment]
Thanks @hzongaro and @r30shah for your valuable suggestions.
I’ve started implementing the changes based on your input, though the approach may evolve as we progress.
Currently, the implementation is relatively straightforward due to the limited number of supported Vector API opcodes. However, as we expand coverage, we expect the complexity to increase significantly.
There are some edge cases that are both scenario and platform specific. For instance, we have overlapping float and vector registers. In cases where a vector result is reduced to a float register, we may need to allocate a float register as a vector register, which introduces additional challenges in register management.

**Comment by r30shah** [comment]
@ehsankianifar  - Please open up an issue on OMR to keep working on this. I am OK with current change, but expect that we do work and propose some broader changes that we are discussing here. 

As I said,  GRA is not the only optimization that can generate regLoad/regStore. We are simply increasing the technical debt here by selectively adding the opcode types.

**Comment by ehsankianifar** [comment]
> @ehsankianifar - Please open up an issue on OMR to keep working on this. I am OK with current change, but expect that we do work and propose some broader changes that we are discussing here.
> 
> As I said, GRA is not the only optimization that can generate regLoad/regStore. We are simply increasing the technical debt here by selectively adding the opcode types.

Thanks @r30shah,
I created this issue as you suggested: https://github.com/eclipse-omr/omr/issues/8012

**Comment by hzongaro** [comment]
Jenkins build all

**Review by r30shah — APPROVED** [review]
LGTM - given that we have an issue opened up to introduce a flag that can provide the information if the node is using VRF/GPR/FPRs.

**Review by hzongaro — APPROVED** [review]

**Comment by hzongaro** [comment]
[linux_ppc-64_le_gcc failure](https://ci.eclipse.org/omr/job/PullRequest-linux_ppc-64_le_gcc/4933) appears to be due to issue #6571
[linux_riscv64 test failure](https://ci.eclipse.org/omr/job/PullRequest-linux_riscv64/466) appears to be due to issue #7971

Merging.
